// Demo catalog for DistroSource Gaming — 20 products across FiveM,
// Minecraft, and platform-agnostic tooling. Tebex fields are placeholders
// until real packages exist (see docs/DATABASE-MIGRATIONS.md context on this
// department being entirely separate from the Polar/PayPal checkout flow).
function tebex(id) {
  return { tebexPackageId: String(id), tebexPackageUrl: `https://distrosource.tebex.io/package/${id}` }
}

export const PRODUCTS = [
  {
    slug: "emerald-bay-luxury-beach-house-mlo",
    name: "Emerald Bay Luxury Beach House MLO",
    tagline: "A fully custom oceanfront estate interior for FiveM roleplay servers.",
    description:
      "Emerald Bay is a hand-built luxury beach house MLO with a two-story interior, private dock, infinity pool, and fully furnished living spaces. Designed for high-end roleplay scenes, VIP housing, or exclusive events. Every room is optimized for performance with clean collision meshes and no FPS impact on live servers.",
    platform: "fivem",
    category: "maps-environments",
    price: "24.99",
    compareAtPrice: "32.99",
    version: "2.1.0",
    compatibility: "FiveM (any framework) — QBCore, ESX, standalone",
    features: [
      "Two-story furnished interior with ocean-view balcony",
      "Private dock and boat spawn point",
      "Custom infinity pool with working water shader",
      "Optimized collisions — no server-side lag",
      "MLO entrance ipl matched to exterior placement",
    ],
    requirements: ["FiveM server build 6000+", "ox_lib or equivalent resource loader", "~40MB server storage"],
    tags: ["mlo", "house", "interior", "luxury", "roleplay"],
    installationGuide:
      "1. Drop the resource folder into your server's resources directory.\n2. Add `ensure emeraldbay_mlo` to your server.cfg.\n3. Restart the resource or reboot the server.\n4. Coordinates and teleport commands are included in the README.",
    changelog: [
      { version: "2.1.0", date: "2025-11-02", notes: "Fixed a clipping issue on the second-floor railing and optimized the pool shader." },
      { version: "2.0.0", date: "2025-08-14", notes: "Added the private dock and boat spawn point." },
      { version: "1.0.0", date: "2025-04-01", notes: "Initial release." },
    ],
    faq: [
      { question: "Does this work with ESX and QBCore?", answer: "Yes — the MLO itself is framework-agnostic; only interior teleports depend on your framework's target/interaction system, and setup notes for both are included." },
      { question: "Will this cause FPS drops on my server?", answer: "No. The interior is built with optimized LODs and collision meshes tested on live servers with 100+ concurrent players." },
    ],
    isFeatured: true,
    isBestseller: true,
    ...tebex(100101),
  },
  {
    slug: "downtown-rooftop-nightclub-mlo",
    name: "Downtown Rooftop Nightclub MLO",
    tagline: "A multi-level nightclub interior with rooftop lounge and VIP areas.",
    description:
      "A dense, atmospheric nightclub MLO spanning a ground-floor dance area, backstage VIP lounge, and open-air rooftop terrace. Built for servers running nightlife, gang, or business roleplay scenarios, with dedicated DJ booth, bar counters, and security checkpoints.",
    platform: "fivem",
    category: "maps-environments",
    price: "29.99",
    version: "1.3.0",
    compatibility: "FiveM (any framework)",
    features: ["3 connected levels", "DJ booth with prop-ready stage", "VIP lounge with private entrance", "Rooftop terrace with skyline view"],
    requirements: ["FiveM server build 5848+", "~55MB server storage"],
    tags: ["mlo", "nightclub", "interior", "business", "roleplay"],
    installationGuide: "Drop into resources/, add `ensure downtown_nightclub_mlo` to server.cfg, restart.",
    changelog: [
      { version: "1.3.0", date: "2025-10-10", notes: "Added rooftop terrace lighting pass." },
      { version: "1.0.0", date: "2025-06-20", notes: "Initial release." },
    ],
    faq: [{ question: "Can I use this as a gang hideout instead?", answer: "Yes, the layout works well for any business-front roleplay concept." }],
    isNew: true,
    ...tebex(100102),
  },
  {
    slug: "sunset-motel-interior-pack",
    name: "Sunset Motel Interior Pack",
    tagline: "Six interconnected motel room interiors for budget roleplay housing.",
    description:
      "A pack of six distinct low-cost motel room interiors, ideal for starter housing, safehouses, or short-stay roleplay. Each room has a unique furniture layout while sharing a consistent worn, roadside-motel aesthetic.",
    platform: "fivem",
    category: "maps-environments",
    price: "19.99",
    version: "1.0.0",
    compatibility: "FiveM (any framework)",
    features: ["6 unique room layouts", "Shared exterior shell for easy placement", "Low prop count for performance"],
    requirements: ["FiveM server build 5700+"],
    tags: ["mlo", "motel", "housing", "interior"],
    installationGuide: "Drop into resources/, add `ensure sunset_motel_pack` to server.cfg, restart.",
    changelog: [{ version: "1.0.0", date: "2025-09-01", notes: "Initial release." }],
    faq: [{ question: "Can each room be sold as separate housing?", answer: "Yes, each interior has its own entrance marker so your housing script can treat them as separate properties." }],
    ...tebex(100103),
  },
  {
    slug: "qbcore-advanced-banking-system",
    name: "QBCore Advanced Banking System",
    tagline: "A full banking overhaul with ATMs, transfers, loans, and statements.",
    description:
      "Replace the default QBCore banking with a full-featured system: ATM interactions, inter-player transfers, business accounts, loan applications with interest, and a transaction history UI. Built to plug directly into existing QBCore economy scripts.",
    platform: "fivem",
    category: "scripts-systems",
    price: "34.99",
    compareAtPrice: "44.99",
    version: "3.0.2",
    compatibility: "FiveM — QBCore framework required",
    features: ["ATM & phone banking UI", "Business account support", "Loan system with configurable interest", "Full transaction history"],
    requirements: ["QBCore framework", "oxmysql", "ox_lib"],
    tags: ["banking", "economy", "qbcore", "script"],
    installationGuide:
      "1. Import the included SQL file.\n2. Drop the resource into resources/[qb]/.\n3. Add `ensure qb-advbanking` after your core resources in server.cfg.\n4. Configure interest rates in config.lua.",
    changelog: [
      { version: "3.0.2", date: "2025-11-20", notes: "Fixed a rounding error on loan interest calculation." },
      { version: "3.0.0", date: "2025-09-15", notes: "Added business account support." },
    ],
    faq: [
      { question: "Does this replace qb-banking entirely?", answer: "Yes, it's a drop-in replacement — remove qb-banking before installing." },
      { question: "Is ESX supported?", answer: "Not currently — this release targets QBCore only." },
    ],
    isFeatured: true,
    isUpdated: true,
    ...tebex(100104),
  },
  {
    slug: "esx-housing-property-management",
    name: "ESX Housing & Property Management",
    tagline: "Buy, sell, and furnish properties with a full real-estate loop.",
    description:
      "A complete property management system for ESX servers: realtor NPC, property listings UI, furniture placement mode, and rent/ownership tracking. Turns housing into a genuine gameplay loop instead of a static teleport list.",
    platform: "fivem",
    category: "scripts-systems",
    price: "39.99",
    version: "2.2.0",
    compatibility: "FiveM — ESX Legacy",
    features: ["Realtor NPC with property listings", "In-game furniture placement mode", "Rent & ownership tracking", "Multi-property support per player"],
    requirements: ["ESX Legacy", "oxmysql"],
    tags: ["housing", "property", "esx", "script"],
    installationGuide: "Import SQL, drop into resources/[esx]/, ensure esx_housing after esx_core in server.cfg.",
    changelog: [{ version: "2.2.0", date: "2025-10-28", notes: "Added multi-property support per player." }],
    faq: [{ question: "Can players rent instead of buy?", answer: "Yes, rent and full-ownership modes are both configurable per property." }],
    isBestseller: true,
    ...tebex(100105),
  },
  {
    slug: "dynamic-vehicle-dealership-script",
    name: "Dynamic Vehicle Dealership Script",
    tagline: "A configurable car dealership with test drives, financing, and trade-ins.",
    description:
      "A vehicle dealership system with a showroom UI, test-drive mode, financing plans, and trade-in valuations. Supports unlimited dealership locations and per-location vehicle catalogs, making it easy to run multiple brand-themed dealerships on one server.",
    platform: "fivem",
    category: "scripts-systems",
    price: "27.99",
    version: "1.5.0",
    compatibility: "FiveM — QBCore or ESX",
    features: ["Showroom UI with vehicle previews", "Test-drive mode with time limit", "Financing plans", "Trade-in valuation"],
    requirements: ["QBCore or ESX", "oxmysql"],
    tags: ["dealership", "vehicles", "economy", "script"],
    installationGuide: "Import SQL, drop into resources/, ensure dyn_dealership in server.cfg, configure catalogs in config.lua.",
    changelog: [{ version: "1.5.0", date: "2025-09-30", notes: "Added trade-in valuation." }],
    faq: [{ question: "Can I run more than one dealership?", answer: "Yes, dealership locations and catalogs are both fully configurable arrays." }],
    ...tebex(100106),
  },
  {
    slug: "modern-minimal-hud-qbcore",
    name: "Modern Minimal HUD — QBCore Edition",
    tagline: "A clean, low-clutter HUD overhaul built for QBCore servers.",
    description:
      "A minimalist HUD replacement showing health, armor, hunger, thirst, stamina, and voice range in a compact, repositionable layout. Includes a settings menu so players can toggle elements and adjust HUD scale without editing config files.",
    platform: "fivem",
    category: "ui-hud",
    price: "14.99",
    version: "1.4.1",
    compatibility: "FiveM — QBCore",
    features: ["Compact repositionable layout", "In-game settings menu", "Voice range indicator", "Low performance impact"],
    requirements: ["QBCore framework"],
    tags: ["hud", "ui", "qbcore"],
    installationGuide: "Drop into resources/[qb]/, ensure qb-minimalhud in server.cfg.",
    changelog: [{ version: "1.4.1", date: "2025-11-05", notes: "Fixed stamina bar not resetting after respawn." }],
    faq: [{ question: "Can players move HUD elements?", answer: "Yes, drag-to-reposition is available from the in-game settings menu." }],
    isNew: true,
    ...tebex(100107),
  },
  {
    slug: "advanced-police-mdt-dispatch-system",
    name: "Advanced Police MDT & Dispatch System",
    tagline: "A full MDT, dispatch board, and 911 call system for law enforcement roleplay.",
    description:
      "A complete law enforcement toolkit: mobile data terminal for record lookups and BOLOs, a dispatch board for active calls, and a 911 system that routes civilian calls to on-duty officers. Built to scale from small whitelisted servers to large public roleplay communities.",
    platform: "fivem",
    category: "ui-hud",
    price: "22.99",
    compareAtPrice: "27.99",
    version: "2.0.1",
    compatibility: "FiveM — QBCore or ESX",
    features: ["MDT with record & BOLO lookups", "Dispatch board for active calls", "911 call routing to on-duty officers"],
    requirements: ["QBCore or ESX", "oxmysql"],
    tags: ["police", "mdt", "dispatch", "ui"],
    installationGuide: "Import SQL, drop into resources/, ensure adv_mdt_dispatch in server.cfg.",
    changelog: [{ version: "2.0.1", date: "2025-10-18", notes: "Fixed BOLO lookups not clearing after arrest." }],
    faq: [{ question: "Does this support EMS as well?", answer: "The dispatch board supports an EMS call channel; the MDT record lookups are law-enforcement only." }],
    isUpdated: true,
    ...tebex(100108),
  },
  {
    slug: "hd-vehicle-livery-pack-vol-1",
    name: "HD Vehicle Livery Pack Vol. 1",
    tagline: "40 high-resolution liveries for popular FiveM vehicle add-ons.",
    description:
      "A collection of 40 clean, high-resolution vehicle liveries covering police, taxi, delivery, and civilian themes. Delivered as ready-to-apply texture files compatible with the most common add-on vehicle packs.",
    platform: "fivem",
    category: "textures-graphics",
    price: "9.99",
    version: "1.0.0",
    compatibility: "FiveM add-on vehicles (compatible model list included)",
    features: ["40 unique livery designs", "4K source textures included", "Police, taxi, delivery, and civilian themes"],
    requirements: ["Add-on vehicle resources already installed"],
    tags: ["livery", "texture", "vehicles"],
    installationGuide: "Copy texture files into your vehicle resource's stream folder and rename per the included mapping sheet.",
    changelog: [{ version: "1.0.0", date: "2025-08-05", notes: "Initial release." }],
    faq: [{ question: "Do you include the base vehicle models?", answer: "No — this pack is liveries only, applied on top of vehicle models you already own." }],
    ...tebex(100109),
  },
  {
    slug: "optimized-server-starter-framework-qbcore",
    name: "Optimized Server Starter Framework (QBCore)",
    tagline: "A performance-tuned QBCore base ready to launch with core jobs and systems pre-configured.",
    description:
      "A ready-to-deploy QBCore server base with core jobs, garages, banking, and inventory pre-configured and performance-tuned. Skip weeks of setup and launch with a stable, tested foundation.",
    platform: "fivem",
    category: "game-server-resources",
    price: "44.99",
    version: "4.1.0",
    compatibility: "FiveM — QBCore framework",
    features: ["Pre-configured core jobs", "Tuned resource load order", "Garage & banking included", "Setup documentation"],
    requirements: ["Fresh FiveM server instance", "MySQL database"],
    tags: ["framework", "server", "qbcore", "starter"],
    installationGuide: "Follow the included setup PDF: import SQL, configure server.cfg, and launch.",
    changelog: [{ version: "4.1.0", date: "2025-11-12", notes: "Updated to latest QBCore core resources and fixed garage sync issue." }],
    faq: [{ question: "Is ongoing support included?", answer: "Setup documentation is included; ongoing customization support is available through DistroSource Support." }],
    isFeatured: true,
    isUpdated: true,
    ...tebex(100110),
  },
  {
    slug: "fivem-roleplay-server-launch-bundle",
    name: "FiveM Roleplay Server Launch Bundle",
    tagline: "Everything needed to launch a roleplay server: framework, MLOs, HUD, and scripts.",
    description:
      "A curated bundle combining the starter framework, three MLO interiors, the minimal HUD, and the banking system — packaged at a discount for anyone launching a new roleplay server from scratch.",
    platform: "fivem",
    category: "gaming-packs",
    price: "69.99",
    compareAtPrice: "94.99",
    version: "1.0.0",
    compatibility: "FiveM — QBCore",
    features: ["Starter framework included", "3 MLO interiors included", "Minimal HUD included", "Banking system included"],
    requirements: ["Fresh FiveM server instance", "MySQL database"],
    tags: ["bundle", "launch", "framework", "qbcore"],
    installationGuide: "Follow the included master setup guide covering each bundled resource in install order.",
    changelog: [{ version: "1.0.0", date: "2025-11-15", notes: "Initial bundle release." }],
    faq: [{ question: "Can I buy the components separately later?", answer: "Yes, each component is also sold individually; the bundle is priced at a discount versus buying separately." }],
    isFeatured: true,
    isBestseller: true,
    ...tebex(100111),
  },
  {
    slug: "skyline-city-modern-metropolis-map",
    name: "Skyline City — Modern Metropolis Map",
    tagline: "A sprawling custom-built city map with skyscrapers, transit, and parks.",
    description:
      "A large-scale custom Minecraft map featuring a modern downtown skyline, subway system, waterfront district, and public parks. Built block-by-block for roleplay, city-building servers, or cinematic builds.",
    platform: "minecraft",
    category: "maps-environments",
    price: "19.99",
    version: "1.2.0",
    compatibility: "Minecraft Java 1.20+",
    features: ["12 detailed skyscrapers", "Working subway layout", "Waterfront district", "Public parks with landscaping"],
    requirements: ["Minecraft Java Edition 1.20+", "~200MB world storage"],
    tags: ["map", "city", "build", "world"],
    installationGuide: "Extract the world folder into your server's root directory and set it as the level-name in server.properties.",
    changelog: [{ version: "1.2.0", date: "2025-10-01", notes: "Added the waterfront district." }],
    faq: [{ question: "Is this survival-ready or creative only?", answer: "It's built for either — chests and item frames are pre-placed for a survival economy setup, but it works equally well in creative." }],
    isNew: true,
    ...tebex(100201),
  },
  {
    slug: "medieval-kingdom-survival-spawn",
    name: "Medieval Kingdom Survival Spawn",
    tagline: "A castle-centered spawn build with village, market, and farmland.",
    description:
      "A medieval-themed spawn area centered on a stone castle, surrounded by a village, open-air market, and farmland. Designed as a welcoming, lore-friendly starting point for survival and roleplay servers.",
    platform: "minecraft",
    category: "maps-environments",
    price: "12.99",
    version: "1.0.0",
    compatibility: "Minecraft Java & Bedrock (converted)",
    features: ["Castle centerpiece", "Village with 15+ buildings", "Open-air market stalls", "Surrounding farmland"],
    requirements: ["Minecraft Java or Bedrock Edition"],
    tags: ["map", "spawn", "medieval", "survival"],
    installationGuide: "Extract the world folder and set as your server's spawn world; schematic version included for single-structure imports.",
    changelog: [{ version: "1.0.0", date: "2025-07-22", notes: "Initial release." }],
    faq: [{ question: "Is a Bedrock version included?", answer: "Yes, a converted .mcworld file is included alongside the Java world folder." }],
    ...tebex(100202),
  },
  {
    slug: "skyblock-server-pack-ready-to-launch",
    name: "SkyBlock Server Pack — Ready to Launch",
    tagline: "A pre-configured SkyBlock server pack with economy, shops, and islands.",
    description:
      "A complete SkyBlock server pack including island generation, an economy plugin pre-configured with a starter shop, and challenge progression. Built to be dropped onto a fresh server and launched the same day.",
    platform: "minecraft",
    category: "game-server-resources",
    price: "29.99",
    version: "2.0.0",
    compatibility: "Minecraft Java — Paper 1.20+",
    features: ["Island generation pre-configured", "Economy & shop plugins included", "Challenge progression system", "Setup guide included"],
    requirements: ["Paper server 1.20+", "~4GB RAM recommended"],
    tags: ["skyblock", "server-pack", "economy"],
    installationGuide: "Copy the plugins folder into your server, review config.yml files, and restart.",
    changelog: [{ version: "2.0.0", date: "2025-10-25", notes: "Rebuilt economy config for Paper 1.20 compatibility." }],
    faq: [{ question: "Does this include island schematics?", answer: "Yes, three starter island schematics are included and configurable in the island plugin's config." }],
    isBestseller: true,
    isUpdated: true,
    ...tebex(100203),
  },
  {
    slug: "survival-server-config-plugin-bundle",
    name: "Survival Server Config & Plugin Bundle",
    tagline: "A ready-made plugin set and configuration for a balanced survival server.",
    description:
      "A curated set of survival server plugins — land claims, grief prevention, an economy, and player warps — with configuration files pre-tuned for a balanced, griefer-resistant survival experience.",
    platform: "minecraft",
    category: "game-server-resources",
    price: "24.99",
    version: "1.1.0",
    compatibility: "Minecraft Java — Paper/Spigot 1.19+",
    features: ["Land claims & grief prevention", "Economy plugin pre-tuned", "Player warps & teleport system"],
    requirements: ["Paper or Spigot server 1.19+"],
    tags: ["survival", "server-pack", "plugins"],
    installationGuide: "Copy the plugins folder into your server directory and restart; config files are pre-filled with recommended values.",
    changelog: [{ version: "1.1.0", date: "2025-09-10", notes: "Tuned grief-prevention claim limits for smaller communities." }],
    faq: [{ question: "Will this work on Spigot without Paper?", answer: "Yes, all included plugins support both Paper and Spigot 1.19+." }],
    ...tebex(100204),
  },
  {
    slug: "realistic-hd-texture-pack-512x",
    name: "Realistic HD Texture Pack 512x",
    tagline: "A high-resolution realistic texture overhaul for immersive builds.",
    description:
      "A 512x resolution texture pack giving blocks, terrain, and foliage a realistic, high-detail look. Well suited for cinematic builds, showcase servers, and screenshot-heavy content creation.",
    platform: "minecraft",
    category: "textures-graphics",
    price: "8.99",
    version: "3.0.0",
    compatibility: "Minecraft Java 1.19+",
    features: ["512x resolution textures", "Realistic terrain & foliage", "Custom PBR normal maps (with supporting shader packs)"],
    requirements: ["Minecraft Java Edition 1.19+", "A capable GPU recommended for 512x resolution"],
    tags: ["texture-pack", "resource-pack", "realistic"],
    installationGuide: "Drop the .zip into your resourcepacks folder and enable it from the in-game resource pack menu.",
    changelog: [{ version: "3.0.0", date: "2025-11-01", notes: "Reworked all foliage textures for 1.19+ block models." }],
    faq: [{ question: "Do I need a shader pack for this to look good?", answer: "No, it looks great on vanilla lighting; a shader pack enhances it further but isn't required." }],
    isUpdated: true,
    ...tebex(100205),
  },
  {
    slug: "pixel-fantasy-resource-pack",
    name: "Pixel Fantasy Resource Pack",
    tagline: "A vibrant stylized resource pack inspired by classic fantasy RPGs.",
    description:
      "A colorful, stylized resource pack that leans into a classic pixel-fantasy look — vibrant blocks, characterful item icons, and a cohesive fantasy palette across the whole pack.",
    platform: "minecraft",
    category: "textures-graphics",
    price: "6.99",
    version: "1.0.0",
    compatibility: "Minecraft Java 1.18+",
    features: ["Vibrant stylized block textures", "Custom item icon set", "Cohesive fantasy color palette"],
    requirements: ["Minecraft Java Edition 1.18+"],
    tags: ["texture-pack", "resource-pack", "fantasy"],
    installationGuide: "Drop the .zip into your resourcepacks folder and enable it from the in-game resource pack menu.",
    changelog: [{ version: "1.0.0", date: "2025-06-15", notes: "Initial release." }],
    faq: [{ question: "Does this include a matching mob texture set?", answer: "Mob textures are included for all vanilla mobs." }],
    ...tebex(100206),
  },
  {
    slug: "custom-minecraft-server-gui-menu-pack",
    name: "Custom Minecraft Server GUI & Menu Pack",
    tagline: "Branded chest-GUI menus for shops, warps, and player settings.",
    description:
      "A set of custom-branded chest-GUI menus covering shop categories, warp selection, and a player settings panel — replacing plain default menus with a cohesive, server-branded interface.",
    platform: "minecraft",
    category: "ui-hud",
    price: "11.99",
    version: "1.2.0",
    compatibility: "Minecraft Java — Paper/Spigot 1.19+",
    features: ["Branded shop category menus", "Warp selection GUI", "Player settings panel"],
    requirements: ["Paper or Spigot server 1.19+", "A menu plugin (Deluxe Menus or equivalent) — config included"],
    tags: ["gui", "menu", "ui"],
    installationGuide: "Import the included menu configuration files into your menu plugin's config folder and restart.",
    changelog: [{ version: "1.2.0", date: "2025-08-20", notes: "Added the player settings panel." }],
    faq: [{ question: "Which menu plugin does this require?", answer: "Configs are provided for Deluxe Menus; instructions for adapting to other menu plugins are included." }],
    ...tebex(100207),
  },
  {
    slug: "minecraft-server-launch-bundle-smp-essentials",
    name: "Minecraft Server Launch Bundle — SMP Essentials",
    tagline: "A complete SMP starter kit: spawn map, plugins, GUI menus, and texture pack.",
    description:
      "Everything needed to launch a small-to-mid SMP server: the medieval spawn map, the survival plugin bundle, the branded GUI menu pack, and the realistic texture pack — bundled at a discount.",
    platform: "minecraft",
    category: "gaming-packs",
    price: "49.99",
    compareAtPrice: "67.99",
    version: "1.0.0",
    compatibility: "Minecraft Java — Paper 1.19+",
    features: ["Spawn map included", "Survival plugin bundle included", "Branded GUI menus included", "Texture pack included"],
    requirements: ["Paper server 1.19+"],
    tags: ["bundle", "smp", "launch", "server-pack"],
    installationGuide: "Follow the included master setup guide covering each bundled resource in install order.",
    changelog: [{ version: "1.0.0", date: "2025-11-18", notes: "Initial bundle release." }],
    faq: [{ question: "Can I swap the spawn map for a different one I own?", answer: "Yes, every component works independently — swap in any world folder you like." }],
    isFeatured: true,
    ...tebex(100208),
  },
  {
    slug: "universal-discord-bot-game-server-management",
    name: "Universal Discord Bot for Game Server Management",
    tagline: "Live server status, player counts, and admin commands, right in Discord.",
    description:
      "A Discord bot that connects to your game server (FiveM, Minecraft, or most others via RCON/query protocols) to post live status, player counts, and let admins run whitelisted commands from a Discord channel.",
    platform: "other",
    category: "game-server-resources",
    price: "17.99",
    version: "1.6.0",
    compatibility: "FiveM, Minecraft, and any RCON/query-compatible server",
    features: ["Live status & player count embed", "Whitelisted admin commands from Discord", "Supports FiveM and Minecraft query protocols"],
    requirements: ["A hosted bot process (Node.js) or DistroSource-provided hosting", "Server RCON/query access"],
    tags: ["discord", "bot", "management", "utility"],
    installationGuide: "Follow the included setup guide to create a Discord application, add your bot token to .env, and run the start script.",
    changelog: [{ version: "1.6.0", date: "2025-11-08", notes: "Added Minecraft query protocol support alongside existing FiveM support." }],
    faq: [{ question: "Do I need to host this myself?", answer: "Yes, a small always-on Node.js process is required; hosting instructions for common providers are included." }],
    isNew: true,
    ...tebex(100301),
  },
]
